server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: hello-service
          uri: http://hello-service:9093
          predicates:
            - Path=/api/hello/**

        - id: producer-service
          uri: http://producer-service:9091
          predicates:
            - Path=/api/producer/**

        - id: consumer-service
          uri: http://consumer-service:9092
          predicates:
            - Path=/api/consumer/**
