apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    app: consumer-service
spec:
  selector:
    app: consumer-service
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP
  type: ClusterIP
