apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  selector:
    app: hello-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP
